name: All Regions Network Benchmark

on:
  schedule:
    - cron: '0 */3 * * *'  # Runs every 3 hours
  workflow_dispatch:  # Allow manual trigger

jobs:
  trigger-regional-workflows:
    name: Trigger All Regional Workflows
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Trigger WebApp workflow
      run: |
        gh workflow run "WebApp workflow" || echo "Failed to trigger WebApp workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Trigger Australia East Network Benchmark
      run: |
        gh workflow run "Australia East Network Benchmark" || echo "Failed to trigger australiaeast workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Austria East Network Benchmark
      run: |
        gh workflow run "Austria East Network Benchmark" || echo "Failed to trigger austriaeast workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Brazil South Network Benchmark
      run: |
        gh workflow run "Brazil South Network Benchmark" || echo "Failed to trigger brazilsouth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Canada Central Network Benchmark
      run: |
        gh workflow run "Canada Central Network Benchmark" || echo "Failed to trigger canadacentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Central India Network Benchmark
      run: |
        gh workflow run "Central India Network Benchmark" || echo "Failed to trigger centralindia workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Central US Network Benchmark
      run: |
        gh workflow run "Central US Network Benchmark" || echo "Failed to trigger centralus workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Chile Central Network Benchmark
      run: |
        gh workflow run "Chile Central Network Benchmark" || echo "Failed to trigger chilecentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger East Asia Network Benchmark
      run: |
        gh workflow run "East Asia Network Benchmark" || echo "Failed to trigger eastasia workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger East US 2 Network Benchmark
      run: |
        gh workflow run "East US 2 Network Benchmark" || echo "Failed to trigger eastus2 workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger France Central Network Benchmark
      run: |
        gh workflow run "France Central Network Benchmark" || echo "Failed to trigger francecentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Germany West Central Network Benchmark
      run: |
        gh workflow run "Germany West Central Network Benchmark" || echo "Failed to trigger germanywestcentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Indonesia Central Network Benchmark
      run: |
        gh workflow run "Indonesia Central Network Benchmark" || echo "Failed to trigger indonesiacentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Israel Central Network Benchmark
      run: |
        gh workflow run "Israel Central Network Benchmark" || echo "Failed to trigger israelcentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Italy North Network Benchmark
      run: |
        gh workflow run "Italy North Network Benchmark" || echo "Failed to trigger italynorth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Japan East Network Benchmark
      run: |
        gh workflow run "Japan East Network Benchmark" || echo "Failed to trigger japaneast workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Japan West Network Benchmark
      run: |
        gh workflow run "Japan West Network Benchmark" || echo "Failed to trigger japanwest workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Korea Central Network Benchmark
      run: |
        gh workflow run "Korea Central Network Benchmark" || echo "Failed to trigger koreacentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Malaysia West Network Benchmark
      run: |
        gh workflow run "Malaysia West Network Benchmark" || echo "Failed to trigger malaysiawest workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Mexico Central Network Benchmark
      run: |
        gh workflow run "Mexico Central Network Benchmark" || echo "Failed to trigger mexicocentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger New Zealand North Network Benchmark
      run: |
        gh workflow run "New Zealand North Network Benchmark" || echo "Failed to trigger newzealandnorth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger North Europe Network Benchmark
      run: |
        gh workflow run "North Europe Network Benchmark" || echo "Failed to trigger northeurope workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Norway East Network Benchmark
      run: |
        gh workflow run "Norway East Network Benchmark" || echo "Failed to trigger norwayeast workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Poland Central Network Benchmark
      run: |
        gh workflow run "Poland Central Network Benchmark" || echo "Failed to trigger polandcentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger South Africa North Network Benchmark
      run: |
        gh workflow run "South Africa North Network Benchmark" || echo "Failed to trigger southafricanorth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger South Central US Network Benchmark
      run: |
        gh workflow run "South Central US Network Benchmark" || echo "Failed to trigger southcentralus workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Southeast Asia Network Benchmark
      run: |
        gh workflow run "Southeast Asia Network Benchmark" || echo "Failed to trigger southeastasia workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Spain Central Network Benchmark
      run: |
        gh workflow run "Spain Central Network Benchmark" || echo "Failed to trigger spaincentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Sweden Central Network Benchmark
      run: |
        gh workflow run "Sweden Central Network Benchmark" || echo "Failed to trigger swedencentral workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger Switzerland North Network Benchmark
      run: |
        gh workflow run "Switzerland North Network Benchmark" || echo "Failed to trigger switzerlandnorth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger UAE North Network Benchmark
      run: |
        gh workflow run "UAE North Network Benchmark" || echo "Failed to trigger uaenorth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger UK South Network Benchmark
      run: |
        gh workflow run "UK South Network Benchmark" || echo "Failed to trigger uksouth workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger West Europe Network Benchmark
      run: |
        gh workflow run "West Europe Network Benchmark" || echo "Failed to trigger westeurope workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger West US 2 Network Benchmark
      run: |
        gh workflow run "West US 2 Network Benchmark" || echo "Failed to trigger westus2 workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

    - name: Trigger West US 3 Network Benchmark
      run: |
        gh workflow run "West US 3 Network Benchmark" || echo "Failed to trigger westus3 workflow"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Wait before next trigger
      run: sleep 30

